// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_EYrIswWvm9cz9CNNHmW-JOg44nQG3rU',
    appId: '1:661257831415:web:9bad46d92e43e2714524f2',
    messagingSenderId: '661257831415',
    projectId: 'flutter-firebase-44247',
    authDomain: 'flutter-firebase-44247.firebaseapp.com',
    storageBucket: 'flutter-firebase-44247.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtDZC9xOGfJY8U7Lht0-wcuyswxsLiBCA',
    appId: '1:661257831415:android:9d6a6f4940569a624524f2',
    messagingSenderId: '661257831415',
    projectId: 'flutter-firebase-44247',
    storageBucket: 'flutter-firebase-44247.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpGI5uRt7U8NbNlHJfWsCKgU8qydS4ZKk',
    appId: '1:661257831415:ios:f27a473ecd9df9334524f2',
    messagingSenderId: '661257831415',
    projectId: 'flutter-firebase-44247',
    storageBucket: 'flutter-firebase-44247.firebasestorage.app',
    androidClientId: '661257831415-i9i17pffk7074j4bld0vt7t2noqj60tc.apps.googleusercontent.com',
    iosClientId: '661257831415-llnsojkfru4u0gq1epe6o8ah1dfd66bo.apps.googleusercontent.com',
    iosBundleId: 'com.example.users',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpGI5uRt7U8NbNlHJfWsCKgU8qydS4ZKk',
    appId: '1:661257831415:ios:f27a473ecd9df9334524f2',
    messagingSenderId: '661257831415',
    projectId: 'flutter-firebase-44247',
    storageBucket: 'flutter-firebase-44247.firebasestorage.app',
    androidClientId: '661257831415-i9i17pffk7074j4bld0vt7t2noqj60tc.apps.googleusercontent.com',
    iosClientId: '661257831415-llnsojkfru4u0gq1epe6o8ah1dfd66bo.apps.googleusercontent.com',
    iosBundleId: 'com.example.users',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_EYrIswWvm9cz9CNNHmW-JOg44nQG3rU',
    appId: '1:661257831415:web:db1c5bc07b7e75644524f2',
    messagingSenderId: '661257831415',
    projectId: 'flutter-firebase-44247',
    authDomain: 'flutter-firebase-44247.firebaseapp.com',
    storageBucket: 'flutter-firebase-44247.firebasestorage.app',
  );
}
